const association = (
  id,
  word,
  category,
  difficulty,
  clues,
  hint,
  acceptedAnswers = [],
  symbol = ''
) => ({
  id,
  word,
  symbol,
  category,
  difficulty,
  clues,
  hint,
  acceptedAnswers,
})

const logic = (
  id,
  mode,
  words,
  answer,
  hint,
  category,
  difficulty,
  acceptedAnswers = []
) => ({
  id,
  mode,
  words,
  answer,
  hint,
  category,
  difficulty,
  acceptedAnswers,
})

const relation = (
  id,
  leftWord,
  rightWord,
  relationType,
  category,
  difficulty,
  hint
) => ({
  id,
  leftWord,
  rightWord,
  relation: relationType,
  category,
  difficulty,
  hint,
})

const chainPreset = (centerWord, starterNodes) => ({
  centerWord,
  starterNodes,
})

export const DEFAULT_ASSOCIATION_WORDS = [
  association(1, 'Atom', 'Nauka', 'Lako', ['Jezgro', 'Elektron', 'Hemija', 'Čestica'], 'Osnovna jedinica materije.', ['atom'], '⚛️'),
  association(2, 'Galaksija', 'Nauka', 'Srednje', ['Zvijezde', 'Svemir', 'Orbita', 'Mliječni put'], 'Ogromna grupa zvijezda i kosmickog materijala.', ['galaksija'], '🌌'),
  association(3, 'Gravitacija', 'Nauka', 'Tesko', ['Pad', 'Privlacnost', 'Masa', 'Njutn'], 'Sila koja privlaci tijela jedno drugom.', ['gravitacija'], '🧲'),
  association(4, 'Fudbal', 'Sport', 'Lako', ['Gol', 'Lopta', 'Stadion', 'Sudija'], 'Sport koji se igra najcesce nogom i loptom.', ['fudbal'], '⚽'),
  association(5, 'Maraton', 'Sport', 'Srednje', ['42 kilometra', 'Izdrzljivost', 'Staza', 'Trkač'], 'Dugacka trkacka disciplina.', ['maraton'], '🏃'),
  association(6, 'Gimnastika', 'Sport', 'Tesko', ['Greda', 'Parter', 'Salto', 'Ravnoteza'], 'Sport koji trazi koordinaciju i kontrolu tijela.', ['gimnastika'], '🤸'),
  association(7, 'Kamera', 'Film', 'Lako', ['Snimanje', 'Objektiv', 'Scena', 'Kadar'], 'Uredjaj bez kojeg nema snimanja filma.', ['kamera'], '🎬'),
  association(8, 'Scenario', 'Film', 'Srednje', ['Dijalog', 'Likovi', 'Zaplet', 'Scenarista'], 'Pisani plan filma ili serije.', ['scenario']),
  association(9, 'Montaza', 'Film', 'Tesko', ['Rez', 'Ritam', 'Postprodukcija', 'Kadrovi'], 'Spajanje i uredjivanje snimljenog materijala.', ['montaza']),
  association(10, 'Piramida', 'Istorija', 'Lako', ['Egipat', 'Faraon', 'Pustinja', 'Grobnica'], 'Gradjevina najpoznatija iz starog Egipta.', ['piramida'], '🔺'),
  association(11, 'Renesansa', 'Istorija', 'Srednje', ['Leonardo', 'Humanizam', 'Firenca', 'Preporod'], 'Istorijski period preporoda umjetnosti i nauke.', ['renesansa']),
  association(12, 'Diplomatija', 'Istorija', 'Tesko', ['Pregovori', 'Ambasada', 'Sporazum', 'Država'], 'Umijece vodjenja medjudrzavnih odnosa.', ['diplomatija']),
  association(13, 'Sunce', 'Priroda', 'Lako', ['Dan', 'Toplota', 'Svjetlost', 'Ljeto'], 'Nebesko tijelo koje nam daje svjetlost i toplotu.', ['sunce'], '☀️'),
  association(14, 'More', 'Priroda', 'Srednje', ['Talas', 'So', 'Plaža', 'Obala'], 'Velika slana vodena povrsina.', ['more'], '🌊'),
  association(15, 'Vulkan', 'Priroda', 'Tesko', ['Lava', 'Krater', 'Erupcija', 'Pepeo'], 'Prirodna pojava povezana sa magmom i erupcijom.', ['vulkan']),
  association(16, 'Simfonija', 'Umjetnost', 'Lako', ['Orkestar', 'Dirigent', 'Stav', 'Muzika'], 'Veliko muzicko djelo za orkestar.', ['simfonija']),
  association(17, 'Skulptura', 'Umjetnost', 'Srednje', ['Klesanje', 'Mermer', 'Figura', 'Vajar'], 'Umjetnicko djelo oblikovano u prostoru.', ['skulptura']),
  association(18, 'Perspektiva', 'Umjetnost', 'Tesko', ['Dubina', 'Linije', 'Prostor', 'Slikarstvo'], 'Likovni princip za prikaz prostora na ravnoj povrsini.', ['perspektiva']),
  association(19, 'Robot', 'Tehnologija', 'Lako', ['Mašina', 'Program', 'Senzor', 'Automatika'], 'Pametna masina koja moze izvrsavati zadatke.', ['robot'], '🤖'),
  association(20, 'Algoritam', 'Tehnologija', 'Srednje', ['Koraci', 'Logika', 'Kod', 'Rjesenje'], 'Niz tacno odredjenih koraka za rjesavanje problema.', ['algoritam']),
  association(21, 'Mikrocip', 'Tehnologija', 'Tesko', ['Procesor', 'Elektronika', 'Ploca', 'Tranzistor'], 'Mala komponenta sa integrisanim kolima.', ['mikrocip', 'mikro cip']),
  association(22, 'Atlas', 'Geografija', 'Lako', ['Karta', 'Kontinent', 'Stranica', 'Planeta'], 'Zbirka geografskih karata.', ['atlas']),
  association(23, 'Arhipelag', 'Geografija', 'Srednje', ['Ostrvo', 'Grupa', 'More', 'Obala'], 'Skup vise ostrva na istom prostoru.', ['arhipelag']),
  association(24, 'Meridijan', 'Geografija', 'Tesko', ['Greenwich', 'Koordinate', 'Polovi', 'Duzina'], 'Zamisljena linija koja spaja polove Zemlje.', ['meridijan']),
  association(25, 'Ćelija', 'Nauka', 'Lako', ['Membrana', 'Jezgro', 'Tkivo', 'Organizam'], 'Osnovna jedinica živih bića.', ['ćelija', 'celija']),
  association(26, 'Kiseonik', 'Nauka', 'Srednje', ['Disanje', 'Gas', 'Vazduh', 'Element'], 'Hemijski element neophodan za disanje.', ['kiseonik']),
  association(27, 'Rukomet', 'Sport', 'Lako', ['Gol', 'Dvorana', 'Sedmerac', 'Lopta'], 'Ekipni sport u kojem se lopta baca rukom.', ['rukomet']),
  association(28, 'Štafeta', 'Sport', 'Srednje', ['Tim', 'Palica', 'Predaja', 'Trka'], 'Trka u kojoj članovi tima predaju palicu.', ['štafeta', 'stafeta']),
  association(29, 'Žanr', 'Film', 'Lako', ['Drama', 'Komedija', 'Horor', 'Vrsta'], 'Vrsta filma ili književnog djela.', ['žanr', 'zanr']),
  association(30, 'Režija', 'Film', 'Tesko', ['Vizija', 'Set', 'Kamera', 'Reditelj'], 'Vođenje i oblikovanje filmskog djela.', ['režija', 'rezija']),
  association(31, 'Ćirilica', 'Istorija', 'Srednje', ['Slova', 'Pismo', 'Azbuka', 'Vuk'], 'Jedno od osnovnih slovenskih pisama.', ['ćirilica', 'cirilica']),
  association(32, 'Pećina', 'Priroda', 'Lako', ['Stijena', 'Mrak', 'Podzemlje', 'Kapljice'], 'Prirodna šupljina u stijeni.', ['pećina', 'pecina']),
  association(33, 'Šuma', 'Priroda', 'Srednje', ['Drveće', 'Lišće', 'Staza', 'Životinje'], 'Veliko područje obraslo drvećem.', ['šuma', 'suma']),
  association(34, 'Pozorište', 'Umjetnost', 'Lako', ['Scena', 'Glumci', 'Publika', 'Predstava'], 'Mjesto i umjetnost izvođenja predstava.', ['pozorište', 'pozoriste']),
  association(35, 'Računar', 'Tehnologija', 'Lako', ['Tastatura', 'Ekran', 'Procesor', 'Miš'], 'Elektronski uređaj za obradu podataka.', ['računar', 'racunar', 'kompjuter']),
  association(36, 'Mreža', 'Tehnologija', 'Srednje', ['Internet', 'Signal', 'Povezivanje', 'Server'], 'Sistem povezanih uređaja i veza.', ['mreža', 'mreza']),
  association(37, 'Ušće', 'Geografija', 'Srednje', ['Rijeka', 'More', 'Ulivanje', 'Delta'], 'Mjesto gdje se rijeka uliva u veću vodenu površinu.', ['ušće', 'usce']),
  association(38, 'Poluostrvo', 'Geografija', 'Tesko', ['Kopno', 'More', 'Rt', 'Obala'], 'Kopno okruženo morem sa tri strane.', ['poluostrvo']),
]

export const DEFAULT_LOGIC_CHALLENGES = [
  logic(1, 'concept', ['Teleskop', 'Planeta', 'Zvijezda'], 'Astronomija', 'Pomisli na nauku koja prouceva svemir.', 'Nauka', 'Lako', ['astronomija', 'nauka o svemiru']),
  logic(2, 'odd-one-out', ['Proton', 'Elektron', 'Neutron', 'Fjord'], 'Fjord', 'Tri pojma pripadaju atomu, jedan geografiji.', 'Nauka', 'Srednje'),
  logic(3, 'concept', ['Masa', 'Pad', 'Privlacnost'], 'Gravitacija', 'Rijesenje je sila koja djeluje izmedju tijela.', 'Nauka', 'Tesko', ['gravitacija', 'sila teze']),
  logic(4, 'concept', ['Gol', 'Lopta', 'Sudija'], 'Fudbal', 'Rijesenje je popularan ekipni sport.', 'Sport', 'Lako', ['fudbal', 'nogomet']),
  logic(5, 'odd-one-out', ['Sprint', 'Maraton', 'Skok', 'Reziser'], 'Reziser', 'Tri pojma su sportske discipline.', 'Sport', 'Srednje'),
  logic(6, 'concept', ['Greda', 'Parter', 'Ravnoteza'], 'Gimnastika', 'Povezi pojmove sa jednim zahtjevnim sportom.', 'Sport', 'Tesko', ['gimnastika', 'sportska gimnastika']),
  logic(7, 'concept', ['Glumac', 'Kadar', 'Scenarista'], 'Film', 'Povezi pojmove sa filmskom industrijom.', 'Film', 'Lako', ['film', 'kinematografija', 'filmska umjetnost']),
  logic(8, 'odd-one-out', ['Kamera', 'Montaza', 'Mikrofon', 'Glacijal'], 'Glacijal', 'Tri pojma pripadaju filmskoj produkciji.', 'Film', 'Srednje'),
  logic(9, 'concept', ['Rez', 'Ritam', 'Postprodukcija'], 'Montaza', 'Rijesenje je dio filmskog procesa nakon snimanja.', 'Film', 'Tesko', ['montaza', 'filmska montaza']),
  logic(10, 'concept', ['Faraon', 'Nil', 'Piramida'], 'Egipat', 'Rijesenje je drevna civilizacija ili drzava.', 'Istorija', 'Lako', ['egipat', 'stari egipat', 'drevni egipat']),
  logic(11, 'odd-one-out', ['Piramida', 'Koloseum', 'Akvadukt', 'Baterija'], 'Baterija', 'Tri pojma su istorijske gradjevine ili ostaci.', 'Istorija', 'Srednje'),
  logic(12, 'concept', ['Pregovori', 'Ambasada', 'Sporazum'], 'Diplomatija', 'Rijesenje opisuje odnose izmedju drzava.', 'Istorija', 'Tesko', ['diplomatija', 'medjudrzavni odnosi']),
  logic(13, 'concept', ['Rijeka', 'Jezero', 'More'], 'Voda', 'Sve pojmove povezuje ista prirodna supstanca.', 'Priroda', 'Lako', ['voda', 'h2o']),
  logic(14, 'odd-one-out', ['Bor', 'Hrast', 'Jela', 'Tablet'], 'Tablet', 'Tri pojma su vrste drveca.', 'Priroda', 'Srednje'),
  logic(15, 'concept', ['Lava', 'Krater', 'Erupcija'], 'Vulkan', 'Povezi pojmove sa jednom prirodnom pojavom.', 'Priroda', 'Tesko', ['vulkan', 'vulkanska erupcija']),
  logic(16, 'concept', ['Dirigent', 'Orkestar', 'Stav'], 'Simfonija', 'Rijesenje je muzicko djelo za orkestar.', 'Umjetnost', 'Lako', ['simfonija', 'orkestarsko djelo']),
  logic(17, 'odd-one-out', ['Violina', 'Klavir', 'Gitara', 'Satelit'], 'Satelit', 'Tri pojma su muzicki instrumenti.', 'Umjetnost', 'Srednje'),
  logic(18, 'concept', ['Dubina', 'Linije', 'Prostor'], 'Perspektiva', 'Rijesenje je likovni princip.', 'Umjetnost', 'Tesko', ['perspektiva', 'prostorni prikaz']),
  logic(19, 'concept', ['Kod', 'Program', 'Aplikacija'], 'Softver', 'Povezi pojmove sa digitalnim proizvodom.', 'Tehnologija', 'Lako', ['softver', 'software', 'program', 'programska oprema']),
  logic(20, 'odd-one-out', ['Procesor', 'Memorija', 'Ekran', 'Pjesma'], 'Pjesma', 'Tri pojma pripadaju tehnologiji ili racunaru.', 'Tehnologija', 'Srednje'),
  logic(21, 'concept', ['Automatika', 'Senzor', 'Mašina'], 'Robotika', 'Rijesenje je tehnoloska oblast.', 'Tehnologija', 'Tesko', ['robotika', 'nauka o robotima']),
  logic(22, 'concept', ['Država', 'Granica', 'Kontinent'], 'Geografija', 'Povezi pojmove sa naukom o prostoru Zemlje.', 'Geografija', 'Lako', ['geografija', 'nauka o zemlji']),
  logic(23, 'odd-one-out', ['Atlas', 'Meridijan', 'Ekvator', 'Scenario'], 'Scenario', 'Tri pojma se vezuju za geografiju.', 'Geografija', 'Srednje'),
  logic(24, 'concept', ['Greenwich', 'Koordinate', 'Polovi'], 'Meridijan', 'Rijesenje je geografski pojam za uzduzne linije.', 'Geografija', 'Tesko', ['meridijan', 'meridijani', 'uzduzne linije']),
  logic(25, 'concept', ['Membrana', 'Jezgro', 'Tkivo'], 'Ćelija', 'Poveži pojmove sa osnovnom jedinicom života.', 'Nauka', 'Lako', ['ćelija', 'celija']),
  logic(26, 'odd-one-out', ['Kiseonik', 'Azot', 'Vodonik', 'Pozorište'], 'Pozorište', 'Tri pojma su hemijski elementi ili gasovi.', 'Nauka', 'Srednje'),
  logic(27, 'concept', ['Palica', 'Predaja', 'Tim'], 'Štafeta', 'Rješenje je trkačka disciplina sa više takmičara.', 'Sport', 'Srednje', ['štafeta', 'stafeta', 'stafetna trka']),
  logic(28, 'concept', ['Sedmerac', 'Golman', 'Dvorana'], 'Rukomet', 'Rješenje je ekipni sport koji se igra rukama.', 'Sport', 'Lako', ['rukomet', 'handball']),
  logic(29, 'concept', ['Drama', 'Komedija', 'Horor'], 'Žanr', 'Sve riječi predstavljaju vrste istog umjetničkog pojma.', 'Film', 'Lako', ['žanr', 'zanr', 'vrsta filma', 'filmski zanr']),
  logic(30, 'odd-one-out', ['Kamera', 'Reditelj', 'Kadar', 'Čempres'], 'Čempres', 'Tri pojma pripadaju filmu, jedan prirodi.', 'Film', 'Tesko'),
  logic(31, 'concept', ['Slova', 'Azbuka', 'Pismo'], 'Ćirilica', 'Rješenje je jedno pismo.', 'Istorija', 'Srednje', ['ćirilica', 'cirilica', 'azbuka']),
  logic(32, 'odd-one-out', ['Šuma', 'Pećina', 'Planina', 'Lozinka'], 'Lozinka', 'Tri pojma pripadaju prirodi.', 'Priroda', 'Lako'),
  logic(33, 'concept', ['Scena', 'Glumci', 'Publika'], 'Pozorište', 'Rješenje povezuje izvođenje predstava.', 'Umjetnost', 'Lako', ['pozorište', 'pozoriste', 'teatar']),
  logic(34, 'concept', ['Tastatura', 'Procesor', 'Miš'], 'Računar', 'Rješenje je uređaj kojem svi pojmovi pripadaju.', 'Tehnologija', 'Lako', ['računar', 'racunar', 'kompjuter', 'komputer']),
  logic(35, 'concept', ['Internet', 'Signal', 'Povezivanje'], 'Mreža', 'Rješenje označava povezan sistem uređaja.', 'Tehnologija', 'Srednje', ['mreža', 'mreza', 'racunarska mreza']),
  logic(36, 'concept', ['Rijeka', 'More', 'Ulivanje'], 'Ušće', 'Rješenje je geografski pojam za završetak toka rijeke.', 'Geografija', 'Srednje', ['ušće', 'usce', 'rijecno usce']),
]

export const DEFAULT_RELATION_CHALLENGES = [
  relation(1, 'Tacan', 'Precizan', 'Sinonim', 'Nauka', 'Lako', 'Obje rijeci opisuju visoku mjeru ispravnosti.'),
  relation(2, 'Hipoteza', 'Teorija', 'Asocijacija', 'Nauka', 'Srednje', 'Pojmovi su blisko povezani u naucnom procesu.'),
  relation(3, 'Stabilan', 'Nestabilan', 'Antonim', 'Nauka', 'Tesko', 'Jedna rijec negira osobinu druge.'),
  relation(4, 'Brz', 'Spor', 'Antonim', 'Sport', 'Lako', 'Pogledaj da li su pojmovi suprotnosti.'),
  relation(5, 'Pobjeda', 'Trijumf', 'Sinonim', 'Sport', 'Srednje', 'Oba pojma opisuju isti ishod.'),
  relation(6, 'Lopta', 'Gol', 'Asocijacija', 'Sport', 'Tesko', 'Pojmovi su povezani u istoj igri.'),
  relation(7, 'Glumac', 'Uloga', 'Asocijacija', 'Film', 'Lako', 'Jedan pojam gotovo uvijek ide uz drugi u filmu.'),
  relation(8, 'Glavni', 'Sporedni', 'Antonim', 'Film', 'Srednje', 'Pojmovi opisuju suprotne uloge ili planove.'),
  relation(9, 'Kadar', 'Scena', 'Asocijacija', 'Film', 'Tesko', 'Povezanost je filmska, ne znacenjska.'),
  relation(10, 'Mir', 'Rat', 'Antonim', 'Istorija', 'Lako', 'Pomisli na suprotnosti.'),
  relation(11, 'Staro', 'Drevno', 'Sinonim', 'Istorija', 'Srednje', 'Rijeci su gotovo isto znacenje.'),
  relation(12, 'Kruna', 'Prijesto', 'Asocijacija', 'Istorija', 'Tesko', 'Oba pojma prizivaju vladara i dvor.'),
  relation(13, 'Topao', 'Hladan', 'Antonim', 'Priroda', 'Lako', 'Rijeci imaju suprotno znacenje.'),
  relation(14, 'Talas', 'More', 'Asocijacija', 'Priroda', 'Srednje', 'Jedan pojam prirodno priziva drugi.'),
  relation(15, 'Suma', 'Gaj', 'Sinonim', 'Priroda', 'Tesko', 'Rijeci oznacavaju vrlo slican pojam.'),
  relation(16, 'Tisina', 'Buka', 'Antonim', 'Umjetnost', 'Lako', 'Jedna rijec iskljucuje drugu.'),
  relation(17, 'Kist', 'Platno', 'Asocijacija', 'Umjetnost', 'Srednje', 'Pojmovi su prirodno povezani u stvaranju slike.'),
  relation(18, 'Inspiracija', 'Ideja', 'Sinonim', 'Umjetnost', 'Tesko', 'Oba pojma ukazuju na pocetak stvaranja.'),
  relation(19, 'Kod', 'Program', 'Asocijacija', 'Tehnologija', 'Lako', 'Jedan pojam je sastavni dio drugog.'),
  relation(20, 'Siguran', 'Nesiguran', 'Antonim', 'Tehnologija', 'Srednje', 'Rijeci imaju suprotan smisao.'),
  relation(21, 'Mikrocip', 'Procesor', 'Asocijacija', 'Tehnologija', 'Tesko', 'Pojmovi su povezani sa racunarskim hardverom.'),
  relation(22, 'Mapa', 'Karta', 'Sinonim', 'Geografija', 'Lako', 'Rijeci se koriste kao isto ili skoro isto.'),
  relation(23, 'Sjever', 'Jug', 'Antonim', 'Geografija', 'Srednje', 'Pojmovi pokazuju suprotne strane svijeta.'),
  relation(24, 'Kompas', 'Pravac', 'Asocijacija', 'Geografija', 'Tesko', 'Jedan pojam sluzi da odredi drugi.'),
  relation(25, 'Tačnost', 'Preciznost', 'Sinonim', 'Nauka', 'Lako', 'Riječi opisuju vrlo sličnu osobinu mjerenja ili rada.'),
  relation(26, 'Živ', 'Mrtav', 'Antonim', 'Nauka', 'Srednje', 'Pojmovi imaju potpuno suprotno značenje.'),
  relation(27, 'Ćelija', 'Tkivo', 'Asocijacija', 'Nauka', 'Tesko', 'Jedan pojam je sastavni dio drugog.'),
  relation(28, 'Štafeta', 'Palica', 'Asocijacija', 'Sport', 'Lako', 'Bez jednog pojma drugi teško može da se zamisli u trci.'),
  relation(29, 'Pobjeda', 'Trijumf', 'Sinonim', 'Sport', 'Srednje', 'Oba pojma znače uspješan ishod.'),
  relation(30, 'Rukomet', 'Dvorana', 'Asocijacija', 'Sport', 'Tesko', 'Pojmovi se prirodno vezuju za isti sport.'),
  relation(31, 'Žanr', 'Vrsta', 'Sinonim', 'Film', 'Lako', 'U ovom kontekstu riječi znače skoro isto.'),
  relation(32, 'Tišina', 'Galama', 'Antonim', 'Umjetnost', 'Srednje', 'Jedan pojam isključuje drugi.'),
  relation(33, 'Pozorište', 'Predstava', 'Asocijacija', 'Umjetnost', 'Tesko', 'Jedan pojam se izvodi u drugom.'),
  relation(34, 'Računar', 'Kompjuter', 'Sinonim', 'Tehnologija', 'Lako', 'Oba pojma označavaju isti uređaj.'),
  relation(35, 'Šifra', 'Lozinka', 'Sinonim', 'Tehnologija', 'Srednje', 'Riječi se koriste za sličan zaštitni pojam.'),
  relation(36, 'Ušće', 'Delta', 'Asocijacija', 'Geografija', 'Tesko', 'Pojmovi su povezani sa završetkom riječnog toka.'),
]

export const DEFAULT_WORD_CHAIN_PRESETS = {
  'Nauka-Lako': chainPreset('Tacnost', [
    { id: 'nauka-lako-1', word: 'Preciznost', relation: 'Sinonim' },
    { id: 'nauka-lako-2', word: 'Greska', relation: 'Antonim' },
    { id: 'nauka-lako-3', word: 'Eksperiment', relation: 'Asocijacija' },
  ]),
  'Nauka-Srednje': chainPreset('Svemir', [
    { id: 'nauka-srednje-1', word: 'Kosmos', relation: 'Sinonim' },
    { id: 'nauka-srednje-2', word: 'Zemlja', relation: 'Antonim' },
    { id: 'nauka-srednje-3', word: 'Galaksija', relation: 'Asocijacija' },
  ]),
  'Nauka-Tesko': chainPreset('Gravitacija', [
    { id: 'nauka-tesko-1', word: 'Privlacnost', relation: 'Sinonim' },
    { id: 'nauka-tesko-2', word: 'Bestezinsko', relation: 'Antonim' },
    { id: 'nauka-tesko-3', word: 'Masa', relation: 'Asocijacija' },
  ]),
  'Sport-Lako': chainPreset('Pobjeda', [
    { id: 'sport-lako-1', word: 'Trijumf', relation: 'Sinonim' },
    { id: 'sport-lako-2', word: 'Poraz', relation: 'Antonim' },
    { id: 'sport-lako-3', word: 'Medalja', relation: 'Asocijacija' },
  ]),
  'Sport-Srednje': chainPreset('Trka', [
    { id: 'sport-srednje-1', word: 'Nadmetanje', relation: 'Sinonim' },
    { id: 'sport-srednje-2', word: 'Mirovanje', relation: 'Antonim' },
    { id: 'sport-srednje-3', word: 'Maraton', relation: 'Asocijacija' },
  ]),
  'Sport-Tesko': chainPreset('Disciplina', [
    { id: 'sport-tesko-1', word: 'Red', relation: 'Sinonim' },
    { id: 'sport-tesko-2', word: 'Nered', relation: 'Antonim' },
    { id: 'sport-tesko-3', word: 'Gimnastika', relation: 'Asocijacija' },
  ]),
  'Film-Lako': chainPreset('Scena', [
    { id: 'film-lako-1', word: 'Prizor', relation: 'Sinonim' },
    { id: 'film-lako-2', word: 'Pauza', relation: 'Antonim' },
    { id: 'film-lako-3', word: 'Kamera', relation: 'Asocijacija' },
  ]),
  'Film-Srednje': chainPreset('Lik', [
    { id: 'film-srednje-1', word: 'Junak', relation: 'Sinonim' },
    { id: 'film-srednje-2', word: 'Publika', relation: 'Antonim' },
    { id: 'film-srednje-3', word: 'Scenario', relation: 'Asocijacija' },
  ]),
  'Film-Tesko': chainPreset('Montaza', [
    { id: 'film-tesko-1', word: 'Sklapanje', relation: 'Sinonim' },
    { id: 'film-tesko-2', word: 'Rasipanje', relation: 'Antonim' },
    { id: 'film-tesko-3', word: 'Rez', relation: 'Asocijacija' },
  ]),
  'Istorija-Lako': chainPreset('Kralj', [
    { id: 'istorija-lako-1', word: 'Vladar', relation: 'Sinonim' },
    { id: 'istorija-lako-2', word: 'Podanik', relation: 'Antonim' },
    { id: 'istorija-lako-3', word: 'Kruna', relation: 'Asocijacija' },
  ]),
  'Istorija-Srednje': chainPreset('Drevno', [
    { id: 'istorija-srednje-1', word: 'Staro', relation: 'Sinonim' },
    { id: 'istorija-srednje-2', word: 'Savremeno', relation: 'Antonim' },
    { id: 'istorija-srednje-3', word: 'Renesansa', relation: 'Asocijacija' },
  ]),
  'Istorija-Tesko': chainPreset('Sporazum', [
    { id: 'istorija-tesko-1', word: 'Dogovor', relation: 'Sinonim' },
    { id: 'istorija-tesko-2', word: 'Sukob', relation: 'Antonim' },
    { id: 'istorija-tesko-3', word: 'Diplomatija', relation: 'Asocijacija' },
  ]),
  'Priroda-Lako': chainPreset('Toplota', [
    { id: 'priroda-lako-1', word: 'Vrucina', relation: 'Sinonim' },
    { id: 'priroda-lako-2', word: 'Hladnoca', relation: 'Antonim' },
    { id: 'priroda-lako-3', word: 'Sunce', relation: 'Asocijacija' },
  ]),
  'Priroda-Srednje': chainPreset('Obala', [
    { id: 'priroda-srednje-1', word: 'Primorje', relation: 'Sinonim' },
    { id: 'priroda-srednje-2', word: 'Pucina', relation: 'Antonim' },
    { id: 'priroda-srednje-3', word: 'More', relation: 'Asocijacija' },
  ]),
  'Priroda-Tesko': chainPreset('Erupcija', [
    { id: 'priroda-tesko-1', word: 'Izlivanje', relation: 'Sinonim' },
    { id: 'priroda-tesko-2', word: 'Mirovanje', relation: 'Antonim' },
    { id: 'priroda-tesko-3', word: 'Vulkan', relation: 'Asocijacija' },
  ]),
  'Umjetnost-Lako': chainPreset('Muzika', [
    { id: 'umjetnost-lako-1', word: 'Melodija', relation: 'Sinonim' },
    { id: 'umjetnost-lako-2', word: 'Tisina', relation: 'Antonim' },
    { id: 'umjetnost-lako-3', word: 'Simfonija', relation: 'Asocijacija' },
  ]),
  'Umjetnost-Srednje': chainPreset('Figura', [
    { id: 'umjetnost-srednje-1', word: 'Oblik', relation: 'Sinonim' },
    { id: 'umjetnost-srednje-2', word: 'Praznina', relation: 'Antonim' },
    { id: 'umjetnost-srednje-3', word: 'Skulptura', relation: 'Asocijacija' },
  ]),
  'Umjetnost-Tesko': chainPreset('Dubina', [
    { id: 'umjetnost-tesko-1', word: 'Prostornost', relation: 'Sinonim' },
    { id: 'umjetnost-tesko-2', word: 'Plitkost', relation: 'Antonim' },
    { id: 'umjetnost-tesko-3', word: 'Perspektiva', relation: 'Asocijacija' },
  ]),
  'Tehnologija-Lako': chainPreset('Program', [
    { id: 'tehnologija-lako-1', word: 'Softver', relation: 'Sinonim' },
    { id: 'tehnologija-lako-2', word: 'Kvar', relation: 'Antonim' },
    { id: 'tehnologija-lako-3', word: 'Robot', relation: 'Asocijacija' },
  ]),
  'Tehnologija-Srednje': chainPreset('Logika', [
    { id: 'tehnologija-srednje-1', word: 'Racunanje', relation: 'Sinonim' },
    { id: 'tehnologija-srednje-2', word: 'Haos', relation: 'Antonim' },
    { id: 'tehnologija-srednje-3', word: 'Algoritam', relation: 'Asocijacija' },
  ]),
  'Tehnologija-Tesko': chainPreset('Procesor', [
    { id: 'tehnologija-tesko-1', word: 'Jezgro', relation: 'Sinonim' },
    { id: 'tehnologija-tesko-2', word: 'Rucni rad', relation: 'Antonim' },
    { id: 'tehnologija-tesko-3', word: 'Mikrocip', relation: 'Asocijacija' },
  ]),
  'Geografija-Lako': chainPreset('Karta', [
    { id: 'geografija-lako-1', word: 'Mapa', relation: 'Sinonim' },
    { id: 'geografija-lako-2', word: 'Nepoznat teren', relation: 'Antonim' },
    { id: 'geografija-lako-3', word: 'Atlas', relation: 'Asocijacija' },
  ]),
  'Geografija-Srednje': chainPreset('Ostrvo', [
    { id: 'geografija-srednje-1', word: 'Ada', relation: 'Sinonim' },
    { id: 'geografija-srednje-2', word: 'Kopno', relation: 'Antonim' },
    { id: 'geografija-srednje-3', word: 'Arhipelag', relation: 'Asocijacija' },
  ]),
  'Geografija-Tesko': chainPreset('Pravac', [
    { id: 'geografija-tesko-1', word: 'Smjer', relation: 'Sinonim' },
    { id: 'geografija-tesko-2', word: 'Lutanje', relation: 'Antonim' },
    { id: 'geografija-tesko-3', word: 'Meridijan', relation: 'Asocijacija' },
  ]),
}
